### ISSUE TITLE
vagrant file available for v2.3.x?

### ISSUE THREAD

**Issue by roncanepa** [PacificBiosciences/Bioinformatics-Training#15]
The wiki still links to a v2.2 version, and despite trying a different url as a guess, no luck.  Google turns up nothing, so I'm guessing not, but just curious if it's been abandoned.

If it was built internally using chef / puppet / etc, would you consider sharing that file to the community instead so that we can update it?  Thank  you.

**Comment by mjhsieh** [comment]
Richard has updated the wiki already, can we close this? :-)

**Comment by roncanepa** [comment]
Sure!  Thank you for your help.
