### ISSUE TITLE
New AHA execution style and parameters

### ISSUE THREAD

**Issue by ebioman** [PacificBiosciences/Bioinformatics-Training#17]
Hello
I encountered a problem today which I was capable to solve with the old way AHA was executed. I have more reads than the 2mio limit and wanted to extend the limit.

pbaha.main.Error: Number of reads: 3485114 exceeds tested maximum of 2000000. Increase the maxNumReads param to allow execution. WARNING: Can crash the host due to high memory use!

I am not afraid to exceed the limit working with 512GB RAM and wanted to extend the limit.
This was previously possible with the xml file but now with the  pbahaScaffolder.py command it tells me that this option does not exist if I add it to my command

pbahaScaffolder.py: error: unrecognized arguments: --maxNumReads 

Any idea how to overcome this ?

**Comment by rhallPB** [comment]
Unfortunately in the re-factoring the parameter did not get exposed to the command line, it can be changed in the code:
<SMR analysis>/analysis/lib/python2.7/pbaha-0.1.0-py2.7-linux-x86_64.egg/pbaha/main.py
line 176:
self.maxNumReads    = 20000

I make not promises as to how changing this may break things though.
