### ISSUE TITLE
jellyfish memory

### ISSUE THREAD

**Issue by lurebgi** [PacificBiosciences/Bioinformatics-Training#20]
Hi,

I had 44X bird (genome size 1.2G) pacbio reads, 50G bp in total. My MHAP settings was:
mhap=-k 15 --num-hashes 1024 --num-min-matches 3 --threshold 0.04

When running jellyfish count (-m 15 -s 120000000 -c 6 -t 16), the memory reached 900G before I killed it. Is there any way to reduce the memory usage in kmer count step? Or can I split the fastq files specifically  for jellyfish, then merge the results and continue the rest steps?

Thanks!

Luohao

**Comment by rhallPB** [comment]
Reducing -s will limit the amount of memory used, are you executing via PBcR? the 120000000 is hardcoded in the script but can be reduced if you are having issues.

**Comment by lurebgi** [comment]
I was running with pacBioToCA. Yes actually I have modified it to 80000000,
but the memory was still up close to 1T. I think I am going to set -s to be
10000000

**Comment by lurebgi** [comment]
Hi, I reduced -s to 10000000, but jellyfish was still running with more than 900G memory. I guess you may consider splitting the fastq in pacBioToCA script to run jellyfish?

**Comment by rhallPB** [comment]
I believe you can reduce -s to something artificially small, the only issue will be a large number of files being created and the possibility of a very slow merge step. My concern is that something is wrong with the data, I have never used more than ~32Gb with a "-s 10000000" even fro very large genomes. Have you sanity checked the data by resequencing against a related bird genome?

**Comment by pb-jchin** [comment]
@lurebgi, you might want to ping the developers of jellyfish or the MHAP's developers too.
