### ISSUE TITLE
AWS AMI unable to select instance r3.8xlarge

### ISSUE THREAD

**Issue by ragowthaman** [PacificBiosciences/Bioinformatics-Training#21]
Hi
I am trying to de-novo assemble an eukaryotic genone using the SMRTPortal AMI in AWS. However, on the Instances list, I see r3.8xlarge is NOT enabled /selectable at all. I tried choosing different AMIs (from 1+ thru 2.3). None enables the powerful machines there. Is it something I am doing incorrectly?  I followed the online instructions religiously. 

c3.8xlarge is enabled, but its computation optimized. Anyone used that for large genomes?

Thanks very much for the attention.
Gowthaman

**Comment by lhon** [comment]
Hi, for large eukaryotic genomes a single node with SMRT Analysis will not be enough computational capacity. We recommend using Falcon (https://github.com/PacificBiosciences/falcon) for larger genomes, which requires a cluster. To use Falcon in the cloud, at the moment DNAnexus might be the easiest way: https://www.dnanexus.com/falcon

**Comment by ragowthaman** [comment]
Hi Ihon,
Thanks so much for the reply. Following your advice, I installed Falcon locally and now attempting to assemble one of the libraries. I have problems there, but, thats another question.

Coming back to this question, one of the genomes I assemble is only 35 MB, we have 8 SMRTcells totalling 600,000 reads (mean length 10 KB). We have assembled a genome like this earlier using HGAP (v1/2). So, it "should" be doable. 

I am attempting to use "c3.8xlarge". Works with 4 smrtcell data. If include more it crashes at /runCaToUnitig step for want of more memory. This aws instance gives maximum of 60GiB memory (32 vCPUs). 

Do I have anyother options in AWS with higher memory.  There are machines, but, when I use PacBio's AMI they are not enabled. Is there a way to enable them?

Another question? How do you compare memory requirement between HGAP2 and 3?

Thanks
Gowthaman

**Comment by lhon** [comment]
What NPROC did you set in smrtpipe.rc? Since you don't have as much memory per core with c3.8xlarge, reducing NPROC down to 16 or even 8 should help here.

Unfortunately at the moment, the only other option to access the higher memory instances I think would be to start a Ubuntu 12.04/14.04 instance and install SMRT Analysis from the tarball here: http://www.pacb.com/support/software-downloads/

HGAP3 is faster and might also be more efficient with memory.

**Comment by ragowthaman** [comment]
I set  NPROC  =  32 (maximum vCPU). But, your suggestion makes sense. I will try that and see how it goes.

ON your second suggestion, We do have a compute cluster locally that has 32 processors + 256 GB mem. Our SMRTPortal instance became unusable once we moved form SGE to SLURM for scheduling.  I had bit of hardtime configuring 2.0 version of SMRTportal (mostly given my limited sysadmin experience).

My question to you is, does SMRTanalysis suite has native SLURM support now? If only SGE is supported, and reducing vCPUs did not work, I have to resort to custom installation in AWS.

**Comment by jrharting** [comment]
We do not officially support SLURM, but our cluster guru has suggested using the following in the template:

salloc --job-name="${JOB_ID}" --nodes=1 --cpus-per-task=${NPROC} srun --cpus-per-task=${NPROC} --ntasks=1 -o ${STDOUT_FILE} -e ${STDERR_FILE} /bin/bash -c "${CMD}"

**Comment by ragowthaman** [comment]
Thanks John. That will be a superuseful first step for me to start
attempting with SLURM. Fantastic.

On Fri, Nov 13, 2015 at 3:13 PM, John Harting <notifications@github.com>
wrote:

> We do not officially support SLURM, but our cluster guru has suggested
> using the following in the template:
>
> salloc --job-name="${JOB_ID}" --nodes=1 --cpus-per-task=${NPROC} srun
> --cpus-per-task=${NPROC} --ntasks=1 -o ${STDOUT_FILE} -e ${STDERR_FILE}
> /bin/bash -c "${CMD}"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PacificBiosciences/Bioinformatics-Training/issues/21#issuecomment-156585392>
> .
>



-- 
Gowthaman Ramasamy PhD.,

Senior Bioinformatics Research Specialist.
*Center for Infectious Disease Research*
307 West lake Ave N Suite 500
Seattle, WA. 98109-5219
Phone : LAB 206-256-7188 (direct).
