### ISSUE TITLE
Can the disk space of the virtual machine be increased?

### ISSUE THREAD

**Issue by JohnYu-yuzhongyi** [PacificBiosciences/Bioinformatics-Training#22]
Hi, 

I'm trying to run SMRT Analysis on a virtual machine based on a Ubuntu server. Now although I can set up the SMRT Analysis, the default disk space of the virtual machine is only less than 40 GB. The server has more space but the virtual machine doesn't take more by default. I tried to run a HGAP2 protocol using 2 SMRT cells and the job failed in the end because of lack of disk space. 

I tried to search for solutions about how to increase disk space of virtualbox but because I'm not familiar with VM I can't fully understand most of them. It looks like there are different types of VM, such as VDI and VMDK and the solutions for them are different. I can't see which type does mine belong to. So I'm quite stuck at the moment.

I wonder does any one knows how to increase the disk space of VM or has anyone had the same problem?

Thanks!

**Comment by rhallPB** [comment]
Did you follow the instructions:
https://github.com/PacificBiosciences/Bioinformatics-Training/wiki/SMRT-Analysis-Virtual-Machine-Install ?
To increase the size of disk using virtual box:
https://www.maketecheasier.com/increase-virtual-hard-disk-size-in-virtualbox/

**Comment by JohnYu-yuzhongyi** [comment]
Thanks rhallPB for answering!

Yes I followed the instructions in the first link.

The second link you gave me suggested a command line input of "VBoxManage modifyhd /path/to/vdi-file --resize x", but I don't have a vdi file. I only have a file called "Vagrantfile". And I tried to put "Vagrantfile" there and it doesn't work. Here's the error shown by command line:

VBoxManage: error: Could not get the storage format of the medium '/data/pacbio/Vagrantfile' (VERR_NOT_SUPPORTED)
VBoxManage: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component Medium, interface IMedium, callee nsISupports
Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, AccessMode_ReadWrite, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 210 of file VBoxManageDisk.cpp

Could you tell me what should I do with this please?

Thanks a million!

**Comment by JohnYu-yuzhongyi** [comment]
Thanks rhallPB!

I've finally managed to increase the disk space in VM by following instructions in this link:
https://gist.github.com/christopher-hopper/9755310

But it looks like I only need to follow it until step 8 because after step 8 my VM has already got increased disk space.
