### ISSUE TITLE
use quiver to further improve the genome

### ISSUE THREAD

**Issue by yilunhuangyue** [PacificBiosciences/Bioinformatics-Training#25]
hello, I have used smrtpipe.py successfully and got polished_assembly.fasta, but I think the quality is not good enough. I want to get a second round of genome polishing by quiver, is there a pipe just like smrtpipe.py? or I need to use pbalign and quiver by myself?
Thanks a lot!

**Comment by jrharting** [comment]
If you have SMRT Portal available, you can import your polished assembly fasta and run RS_Resequencing with your original input data.

**Comment by rhallPB** [comment]
`smrtpipe.py --examples` will return the location of an example directory that outlines how to run resequencing. The polished_assembly.fasta will have to be imported using the `referenceUploader` command first.
