### ISSUE TITLE
what reads were used for de novo assembly?

### ISSUE THREAD

**Issue by lamz138138** [PacificBiosciences/Bioinformatics-Training#33]
Hi!

I have some questions about the reads used for de novo assembly. Suppose I get several bax.h5 files, then how can I get reads for de novo assembly? I can change this file to bam with bax2bam (subreads), then get the CCS reads with pbccs. Also, I can get reads by run smrt pip with P_Filter and P_CCS module. The CCS reads I got would be high quality, but it would be short. So, I think I can use subreads from bax2bam or just run P_Filter module. But several problems here. These subreads may come from the same ZMW, how could I filter out reads from the same ZMW but belong to more than one ROI? Second, the quality of these subreads is worse than CCS, how should I filter bad reads? Third, if I made a long library (the ROI is 30K), would be there only a few reads have one full pass?  In this case, what reads should I use.

Any suggestion would be grateful!

Best wishes!

**Comment by rhallPB** [comment]
For more information: 
[https://github.com/PacificBiosciences/Bioinformatics-Training/wiki/HGAP](url)
[http://www.nature.com/nmeth/journal/v10/n6/abs/nmeth.2474.html](url)

**Comment by lamz138138** [comment]
Thanks very much!
