### ISSUE TITLE
inconsistent assemblies

### ISSUE THREAD

**Issue by mjfi2sb3** [PacificBiosciences/Bioinformatics-Training#34]
Hi,
I received an assembly for a microbial genome that was done using the SMRT portal pipeline. I also assembled the same data using the smrtpipe commandline.

When I compared the assemblies,

1. they were of slightly different sizes: a) 7441978 b) 7450029

2. the dotplot of the two assemblies against each other was a little interesting...see

![j16 sb vs bcl](https://cloud.githubusercontent.com/assets/16022611/19323305/0be38016-90c5-11e6-88c1-ebd04901a05d.jpg)

3. the dotplot of the genome against itself produces a single diagonal line...see below

![j16](https://cloud.githubusercontent.com/assets/16022611/19323420/7fc040f0-90c5-11e6-9264-268a1ca1425c.jpg)

Am I looking at a circular genome? if yes how do I circularise it if the dotplot of the assembly against itself doesn't show it?

Many thanks
/SB

**Comment by rhallPB** [comment]
The first dot plot looks correct, in two assemblies the origin of the two linear sequences does not necessarily have to be the same. It's the same sequence, just starting at different points. 
For the self dot plot, if you zoom in the bottom right, it looks like there is a circular overlap.
[https://github.com/PacificBiosciences/Bioinformatics-Training/wiki/Evaluating-Assemblies](url)
[https://github.com/PacificBiosciences/Bioinformatics-Training/wiki/Circularizing-and-trimming](url)

**Comment by mjfi2sb3** [comment]
Thanks...that's what I thought.

However I can't see what you saw in the bottom-right of the self dotplot!

/SB

**Comment by rhallPB** [comment]
Sorry, bottom left.

**Comment by mjfi2sb3** [comment]
may be I am reading the plot wrong but there are no line in the bottom left either. Anyway, I went ahead and circularised using minimus2 (as explained in the tutorial). It seems to has worked! hay! 

Many thanks

/SB

**Comment by mjfi2sb3** [comment]
OK...I can see it now.

again, many thanks/SB
