### ISSUE TITLE
resequencing protocol error

### ISSUE THREAD

**Issue by mjfi2sb3** [PacificBiosciences/Bioinformatics-Training#36]
Hi @rhallPB ,

This is actually a follow up on issue #35 which was about minimus2 failing to overlap & circularise the genome.

I am following your advice and I have tried to carry out the resequencing protocol using the smrtpipe.py commandline. I did the following:

1. `referenceUploader -c -p references/ -n 44_00 -f circularise/polished_assembly.44.circ.fasta`
2. I copied the params.xml file from the example `/software/smrtanalysis/v2.3.0.140936.p5.app/current/doc/examples/smrtpipe_resequencing`
3. modified the params.xml file with the new reference directory (attached 
[input.44_120.00.xml.txt](https://github.com/PacificBiosciences/Bioinformatics-Training/files/536181/input.44_120.00.xml.txt)
)
4. `smrtpipe.py --params=params.reseq.44.xml --output=$PWD/reseq.44 -D NPROC=64 xml:input.44_120.00.xml`
The input.xxx.xml file contains data references to the XXX.bax.h5 raw files

The job fails after it has run for a few hours...see attached master.log ([master.log.txt](https://github.com/PacificBiosciences/Bioinformatics-Training/files/536179/master.log.txt))

Again, your help is greatly appreciated
/SB

**Comment by rhallPB** [comment]
That should have worked, but for some reason the fasta index file is missing from the reference. You should be able to run `samtools faidx references/44_00/sequence/44_00.fasta` to generate it.

**Comment by mjfi2sb3** [comment]
thanks for your help. That fixed the problem.

I compared the initial circularised assembly against the new consensus, there is a small difference in sequence...for some, the consensus was a little shorter. For others, the consensus was longer.

Following your tips, I will re-run the resequencing protocol starting from the consensus from the previous run and if the new consensus is identical to the input consensus then I take the last input as final assembly? 

Also, is it possible to visualise the difference between the input reference and the consensus?

Best,
/SB

**Comment by mjfi2sb3** [comment]
thanks!
