### ISSUE TITLE
all links broken at Bioinformatics-Workshop

### ISSUE THREAD

**Issue by piatekmj** [PacificBiosciences/Bioinformatics-Training#40]
It seems there has been some change made on the web server side and now all your links under [Bioinformatics-Workshop Webinars](https://github.com/PacificBiosciences/Bioinformatics-Training/wiki/Bioinformatics-Workshop#bioinformatics-workshop-webinars) redirect to new vendor home page.

**Comment by rhallPB** [comment]
Thanks for pointing this out. I've removed the bad links and redirected to the pacb.com training site. Some new, up to date, webinars are being prepared and I'll update once they are available.
