### ISSUE TITLE
assembled genome size supported by HGAP in SMRT-analysis v2.3

### ISSUE THREAD

**Issue by yilunhuangyue** [PacificBiosciences/Bioinformatics-Training#41]
Hi, I want to know the largest genome size supported by HGAP in SMRT-analysis v2.3. The largest published genome assembled by HGAP is  Oropetium thomaeum(genome size is 245M). So can HGAP support larger genome size(>300M or more)? Is there any references?
Thanks a lot for any help~

**Comment by rhallPB** [comment]
HGAP.3 will struggle to assemble >300Mb genomes, it is not computationally efficient enough. The current recommendation would be to use Falcon [https://github.com/PacificBiosciences/Falcon](https://github.com/PacificBiosciences/Falcon) [http://pb-falcon.readthedocs.io/en/latest/](http://pb-falcon.readthedocs.io/en/latest/) [Chin et al. Phased diploid genome assembly with single-molecule real-time sequencing. Nat. Meth. 17 Oct 2016](http://www.nature.com/nmeth/journal/v13/n12/full/nmeth.4035.html).
