### ISSUE TITLE
files

### ISSUE THREAD

**Issue by bifidoman** [PacificBiosciences/Bioinformatics-Training#44]
Hi

I installed the VM for the SMRZ at my mac. This works and I am able to login in at the portal at http://localhost:8080. However, I cannot find my data. There is a dropbox folder (I am not allowed to use, offically), or I can add a folder. However, all my paths are "not found". How does this part work?
thanks

Marc

**Comment by rhallPB** [comment]
Files in the working director on the host machine should be shared under `/vargrant` location on the VM.

**Comment by bifidoman** [comment]
Hi

I did that (/vagrant), and the fold is listed in the VM under shared files. However, the SMRT portal does not recognise any path. 
Should SMRT data be in the folder, or should the folder be recognised without data?

**Comment by bifidoman** [comment]
hi

found it. The path "/" worked and I found my data.

**Comment by bifidoman** [comment]
I got it running. 
Maybe one recommendation. Changing the Vagrantfile to enhance memory seems only to work in a script editor for RUBY (I used textmate). Normal text editing caused a failure each time after "vagrant up"
