### ISSUE TITLE
Reference-assisted assembly with HGAP?

### ISSUE THREAD

**Issue by Nandita-ust** [PacificBiosciences/Bioinformatics-Training#49]
I'm using HGAP via SMRT Link Analysis GUI portal (v.5.0.1).
I have Pacbio data generated from a pool of sheared PCR amplicons, which originate from a 60 kb linear locus.

When I conduct a Resequencing analysis, I get 100% coverage of the reference region, at ~2000x avg coverage. (Coverage is not very uniform, with peaks of ~4000x, in the central regions where the pcr amplicons overlapped by design)

However, if I use the same set of reads to create a denovo assembly using HGAP, I recover ~80% of the reference. Specifically, the assembly is missing ~10 kb at the 5' end and another ~1 kb at the 3' end of the reference.  
I imagine that this has something to do with the coverage and the source being PCR-amplified template.

This 80% coverage assembly is an improvement over a previous assembly that recovered ~50% of the reference (using default parameters of HGAP) and this was achieved by restricting subread length to 3 kb, and turning on "concordant alignment" and "aggressive option" parameters.

(My eventual goal is to assemble these reads and delineate haplotigs using Falcon, but I am playing with HGAP while I get my Falcon installation issues sorted)

Are there any specific parameters that I can tweak to further improve the assembly?
Is there a way I can provide a reference to guide the assembly by Hgap?

**Comment by gconcepcion** [comment]
Hi Nandita-ust,

Unfortunately assembling amplicon data using FALCON or HGAP4 is outside of the scope of the algorithm. 

See this section of the FALCON docs for details:

http://pb-falcon.readthedocs.io/en/latest/faq.html#why-does-falcon-have-trouble-assembling-my-amplicon-data

**Comment by Nandita-ust** [comment]
Thanks Greg.
-Nandita
